# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Kristoffer Jälén AB'
url:              https://jalen.se
baseurl:          /

plugins:
  - jekyll-seo-tag