# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            d018
tagline:          'Blog'
description:      'Random thoughts about the demoscene, .NET, C#, Amiga and the C64.'
url:              http://kristofferjalen.github.io
baseurl:          /

author:
  name:           'Kristoffer Jälén'
  url:            https://twitter.com/kristofferjalen

paginate:         5

gems:             [jekyll-paginate]

# Custom vars
#version:          2.1.0

#github:
  #repo:           https://github.com/kristofferjalen/hyde
